routes:
  unknown-error-alerts:
    matchers:
      title: ["stats"]
      unknown-error: [ "*" ]
    output:
      type: "alerts"
      series: "kinesis-consumer.notifications.unknown-error"
      dimensions: [ ]
      value_field: "unknown-error" 
      stat_type: "counter"
